# Generated by Django 5.2.5 on 2025-09-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_alter_mysuperuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysuperuser',
            name='profile_picture',
            field=models.TextField(default=None, null=True),
        ),
    ]
